// AppRoutes.jsx
import React from 'react';
import { Route, Routes } from 'react-router-dom';
import cities from '../data/cities.js';
import App from '../App.jsx';
import SalesforceConsulting from '../pages/Salesforceconsulting/Salesforceconsulting.jsx';
import Aboutpage from '../pages/Aboutus/Aboutus.jsx';
import Servicespage from '../pages/Services/Servicespage.jsx';
import Testimonialspage from '../pages/Testimonialspage/Testimonialspage.jsx';
import Contactpage from '../pages/Contactpage/Contactpage.jsx';
import Allblogspage from '../pages/Allblogspage/Allblogspage.jsx';

import Salesforceimplementation from '../pages/SEO/Salesforceimplementation.jsx';

const AppRoutesbackup = () => (
  <Routes>
    <Route path="/" element={<App />} />
    <Route path="/about-us" element={<Aboutpage />} />
    <Route path="/services" element={<Servicespage />} />
    <Route path="/testimonials" element={<Testimonialspage />} />
    <Route path="/blogs" element={<Allblogspage />} />
    <Route path="/contact-us" element={<Contactpage />} />
    {/* Salesforce */}
    <Route path="/salesforce-implementation.html" element={<Salesforceimplementation />} />
    <Route path="/salesforce-integration" element={<SalesforceConsulting />} />
    <Route path="/salesforce-customization" element={<SalesforceConsulting />} />
    <Route path="/salesforce-migration" element={<SalesforceConsulting />} />
    <Route path="/salesforce-training" element={<SalesforceConsulting />} />
    <Route path="/salesforce-support" element={<SalesforceConsulting />} />
    <Route path="/salesforce-optimization" element={<SalesforceConsulting />} />
    <Route path="/salesforce-automation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-lightning-migration" element={<SalesforceConsulting />} />
    <Route path="/salesforce-einstein-analytics" element={<SalesforceConsulting />} />
    <Route path="/salesforce-cpq-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-field-service-lightning" element={<SalesforceConsulting />} />
    <Route path="/salesforce-community-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-commerce-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-health-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-financial-services-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-manufacturing-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-consumer-goods-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-nonprofit-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-education-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-government-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-pardot-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-marketing-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-service-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-experience-cloud" element={<SalesforceConsulting />} />
    <Route path="/salesforce-consulting-services" element={<SalesforceConsulting />} />
    <Route path="/salesforce-advisory-services" element={<SalesforceConsulting />} />
    <Route path="/salesforce-managed-services" element={<SalesforceConsulting />} />
    <Route path="/salesforce-adoption-and-change-management" element={<SalesforceConsulting />} />
    <Route path="/salesforce-data-migration" element={<SalesforceConsulting />} />
    <Route path="/salesforce-data-integration" element={<SalesforceConsulting />} />
    <Route path="/salesforce-process-automation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-reporting-and-analytics" element={<SalesforceConsulting />} />
    <Route path="/salesforce-mobile-solutions" element={<SalesforceConsulting />} />
    <Route path="/salesforce-security-and-compliance" element={<SalesforceConsulting />} />
    <Route path="/salesforce-org-optimization" element={<SalesforceConsulting />} />
    <Route path="/salesforce-roadmap-and-strategy" element={<SalesforceConsulting />} />
    <Route path="/salesforce-user-training-and-adoption" element={<SalesforceConsulting />} />
    <Route path="/salesforce-appexchange-solutions" element={<SalesforceConsulting />} />
    <Route path="/salesforce-b2b-commerce" element={<SalesforceConsulting />} />
    <Route path="/salesforce-b2c-commerce" element={<SalesforceConsulting />} />
    <Route path="/salesforce-manufacturing-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-financial-services-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-healthcare-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-nonprofit-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-education-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-government-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-sustainability-cloud-implementation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-loyalty-management" element={<SalesforceConsulting />} />
    <Route path="/salesforce-partner-relationship-management" element={<SalesforceConsulting />} />
    <Route path="/salesforce-customer-360-platform" element={<SalesforceConsulting />} />
    <Route path="/salesforce-integration-with-legacy-systems" element={<SalesforceConsulting />} />
    <Route path="/salesforce-ecosystem-consulting" element={<SalesforceConsulting />} />
    <Route path="/salesforce-agile-transformation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-devops-and-release-management" element={<SalesforceConsulting />} />
    <Route path="/salesforce-predictive-analytics" element={<SalesforceConsulting />} />
    <Route path="/salesforce-intelligent-automation" element={<SalesforceConsulting />} />
    <Route path="/salesforce-conversational-ai" element={<SalesforceConsulting />} />
    <Route path="/salesforce-omnichannel-engagement" element={<SalesforceConsulting />} />
    {/* Web Desgining */}
    <Route path="/website-design" element={<SalesforceConsulting />} />
    <Route path="/website-designing" element={<SalesforceConsulting />} />
    <Route path="/website-development" element={<SalesforceConsulting />} />
    <Route path="/web-development" element={<SalesforceConsulting />} />
    <Route path="/web-designer" element={<SalesforceConsulting />} />
    <Route path="/website-creation" element={<SalesforceConsulting />} />
    <Route path="/web-development-company" element={<SalesforceConsulting />} />
    <Route path="/cms-web-design-services" element={<SalesforceConsulting />} />
    <Route path="/cms-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/cms-website-design-company" element={<SalesforceConsulting />} />
    <Route path="/cms-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/coda-web-development" element={<SalesforceConsulting />} />
    <Route path="/codeigniter-development" element={<SalesforceConsulting />} />
    <Route path="/codeigniter-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/codeigniter-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/complete-web-design" element={<SalesforceConsulting />} />
    <Route path="/corporate-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/creative-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-angularjs-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-ecommerce-web-design-service" element={<SalesforceConsulting />} />
    <Route path="/custom-ecommerce-web-design-services" element={<SalesforceConsulting />} />
    <Route path="/custom-ecommerce-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-ecommerce-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/custom-laravel-development" element={<SalesforceConsulting />} />
    <Route path="/custom-laravel-web-development" element={<SalesforceConsulting />} />
    <Route path="/custom-php-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-php-web-development" element={<SalesforceConsulting />} />
    <Route path="/custom-php-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-web-development-solutions" element={<SalesforceConsulting />} />
    <Route path="/custom-wordpress-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/custom-wordpress-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/digital-kangaroos-web-development-marketing-agency" element={<SalesforceConsulting />} />
    <Route path="/digital-marketing-and-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/digital-marketing-and-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/digital-web-development" element={<SalesforceConsulting />} />
    <Route path="/discord-for-web-developers" element={<SalesforceConsulting />} />
    <Route path="/dot-net-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/drupal-cms-development-company" element={<SalesforceConsulting />} />
    <Route path="/drupal-ecommerce-agency" element={<SalesforceConsulting />} />
    <Route path="/drupal-seo-agency" element={<SalesforceConsulting />} />
    <Route path="/drupal-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/dynamic-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-web-development-solutions" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-website-design-development-company" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-website-design-development-services" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-website-design-and-development-services" element={<SalesforceConsulting />} />
    <Route path="/enterprise-ecommerce-development" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-application-development" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-software-development" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-solutions" element={<SalesforceConsulting />} />
    <Route path="/expert-web-technologies" element={<SalesforceConsulting />} />
    <Route path="/find-web-development-companies" element={<SalesforceConsulting />} />
    <Route path="/flash-web-development" element={<SalesforceConsulting />} />
    <Route path="/freelance-offshore-web-design-developers" element={<SalesforceConsulting />} />
    <Route path="/groovy-web-llp" element={<SalesforceConsulting />} />
    <Route path="/gt-webdev" element={<SalesforceConsulting />} />
    <Route path="/healthcare-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/html5-app-development-services" element={<SalesforceConsulting />} />
    <Route path="/html5-development-company" element={<SalesforceConsulting />} />
    <Route path="/html5-development-services" element={<SalesforceConsulting />} />
    <Route path="/html5-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/jamstack-development-company" element={<SalesforceConsulting />} />
    <Route path="/joomla-development-company" element={<SalesforceConsulting />} />
    <Route path="/joomla-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/joomla-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/joomla-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/joomla-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/laravel-app-development-company" element={<SalesforceConsulting />} />
    <Route path="/laravel-web-app-development" element={<SalesforceConsulting />} />
    <Route path="/leading-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/magento-2-web-development-agency" element={<SalesforceConsulting />} />
    <Route path="/magento-ecommerce-development-agency" element={<SalesforceConsulting />} />
    <Route path="/magento-ecommerce-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/magento-pwa-development-company" element={<SalesforceConsulting />} />
    <Route path="/magento-pwa-development-services" element={<SalesforceConsulting />} />
    <Route path="/magento-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/magento-web-design-services" element={<SalesforceConsulting />} />
    <Route path="/magento-website-design-company" element={<SalesforceConsulting />} />
    <Route path="/matrimony-website-development" element={<SalesforceConsulting />} />
    <Route path="/mobile-web-application-development-services" element={<SalesforceConsulting />} />
    <Route path="/mobile-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/mobile-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/mobile-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/mobile-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/msk-web-development" element={<SalesforceConsulting />} />
    <Route path="/offshore-php-development-company" element={<SalesforceConsulting />} />
    <Route path="/offshore-php-development-services" element={<SalesforceConsulting />} />
    <Route path="/outsource-web-design-services" element={<SalesforceConsulting />} />
    <Route path="/php-application-development-services" element={<SalesforceConsulting />} />
    <Route path="/php-web-application-development-company" element={<SalesforceConsulting />} />
    <Route path="/php-web-application-development-services" element={<SalesforceConsulting />} />
    <Route path="/piccosoft-app" element={<SalesforceConsulting />} />
    <Route path="/professional-custom-web-design" element={<SalesforceConsulting />} />
    <Route path="/professional-web-design-development-company" element={<SalesforceConsulting />} />
    <Route path="/professional-website-design-and-development-services" element={<SalesforceConsulting />} />
    <Route path="/progressive-web-app-development-services" element={<SalesforceConsulting />} />
    <Route path="/pwa-app-development-company" element={<SalesforceConsulting />} />
    <Route path="/pwa-development-services" element={<SalesforceConsulting />} />
    <Route path="/python-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/react-company-website" element={<SalesforceConsulting />} />
    <Route path="/react-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/reactjs-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/responsive-website-developer" element={<SalesforceConsulting />} />
    <Route path="/restaurant-web-design-companies" element={<SalesforceConsulting />} />
    <Route path="/ror-development" element={<SalesforceConsulting />} />
    <Route path="/ruby-on-rails-web" element={<SalesforceConsulting />} />
    <Route path="/ruby-on-rails-web-application" element={<SalesforceConsulting />} />
    <Route path="/ruby-on-rails-website-development" element={<SalesforceConsulting />} />
    <Route path="/seo-and-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/seo-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/seo-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/shopify-ecommerce-development-agency" element={<SalesforceConsulting />} />
    <Route path="/shopify-ecommerce-development-company" element={<SalesforceConsulting />} />
    <Route path="/shopify-web-design-and-development" element={<SalesforceConsulting />} />
    <Route path="/skaro-web-development-studio" element={<SalesforceConsulting />} />
    <Route path="/small-business-web-development-agency" element={<SalesforceConsulting />} />
    <Route path="/small-business-website-design-and-management-services" element={<SalesforceConsulting />} />
    <Route path="/small-business-website-design-companies" element={<SalesforceConsulting />} />
    <Route path="/small-business-website-development-services" element={<SalesforceConsulting />} />
    <Route path="/small-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/software-and-website-development-companies" element={<SalesforceConsulting />} />
    <Route path="/ssg-web-development" element={<SalesforceConsulting />} />
    <Route path="/startup-web-app-development-agency" element={<SalesforceConsulting />} />
    <Route path="/technource" element={<SalesforceConsulting />} />
    <Route path="/top-web-mobile-app-development-company" element={<SalesforceConsulting />} />
    <Route path="/the-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/top-10-web-design-companies-in-the-world" element={<SalesforceConsulting />} />
    <Route path="/top-ecommerce-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/top-front-end-development-companies" element={<SalesforceConsulting />} />
    <Route path="/top-magento-agency" element={<SalesforceConsulting />} />
    <Route path="/top-php-development-companies" element={<SalesforceConsulting />} />
    <Route path="/top-web-and-mobile-app-development-company" element={<SalesforceConsulting />} />
    <Route path="/top-web-design-and-development-companies" element={<SalesforceConsulting />} />
    <Route path="/real-estate-web-design-company" element={<SalesforceConsulting />} />
    <Route path="/best-web-app-development-company" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-development-solutions" element={<SalesforceConsulting />} />
    <Route path="/offshore-web-development-services" element={<SalesforceConsulting />} />
    <Route path="/cheap-website-design-services" element={<SalesforceConsulting />} />
    <Route path="/seo-for-web-developers" element={<SalesforceConsulting />} />
    <Route path="/shopify-ecommerce-development" element={<SalesforceConsulting />} />
    <Route path="/upwork-web-development" element={<SalesforceConsulting />} />
    <Route path="/best-websites-for-software-developers" element={<SalesforceConsulting />} />
    <Route path="/web-designing-companies-near-me" element={<SalesforceConsulting />} />
    <Route path="/web-development-for-startups" element={<SalesforceConsulting />} />
    <Route path="/enterprise-website-development" element={<SalesforceConsulting />} />
    <Route path="/best-web-design-companies-in-the-world" element={<SalesforceConsulting />} />
    <Route path="/web-and-mobile-app-development-services" element={<SalesforceConsulting />} />
    <Route path="/web-application-company" element={<SalesforceConsulting />} />
    <Route path="/magento-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/web-design-company-website" element={<SalesforceConsulting />} />
    <Route path="/web-design-development-agency" element={<SalesforceConsulting />} />
    <Route path="/world-best-website-design-company" element={<SalesforceConsulting />} />
    <Route path="/custom-made-websites-near-me" element={<SalesforceConsulting />} />
    <Route path="/biggest-web-design-companies" element={<SalesforceConsulting />} />
    <Route path="/web-development-services-website" element={<SalesforceConsulting />} />
    <Route path="/best-web-application-development-software" element={<SalesforceConsulting />} />
    <Route path="/website-startup-costs" element={<SalesforceConsulting />} />
    <Route path="/custom-web-app-developers" element={<SalesforceConsulting />} />
    <Route path="/online-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/custom-web-design-and-development" element={<SalesforceConsulting />} />
    <Route path="/drupal-web-design-agency" element={<SalesforceConsulting />} />
    <Route path="/outsource-laravel-development" element={<SalesforceConsulting />} />
    <Route path="/custom-web-design-near-me" element={<SalesforceConsulting />} />
    <Route path="/best-real-estate-developer-websites" element={<SalesforceConsulting />} />
    <Route path="/web-design-companies-for-small-businesses" element={<SalesforceConsulting />} />
    <Route path="/interactive-website-development" element={<SalesforceConsulting />} />
    <Route path="/top-web-app-development-companies" element={<SalesforceConsulting />} />
    <Route path="/wordpress-ecommerce-agency" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-app-development" element={<SalesforceConsulting />} />
    <Route path="/web-design-company-services-london" element={<SalesforceConsulting />} />
    <Route path="/web-development-agency-company" element={<SalesforceConsulting />} />
    <Route path="/for-web-developer" element={<SalesforceConsulting />} />
    <Route path="/front-end-developer-fiverr" element={<SalesforceConsulting />} />
    <Route path="/web-development-companies-in-the-world" element={<SalesforceConsulting />} />
    <Route path="/enterprise-web-application" element={<SalesforceConsulting />} />
    <Route path="/creative-website-development-company" element={<SalesforceConsulting />} />
    <Route path="/backend-development-company" element={<SalesforceConsulting />} />
    <Route path="/freelance-ecommerce-website-developer" element={<SalesforceConsulting />} />
    <Route path="/design-and-development-company" element={<SalesforceConsulting />} />
    <Route path="/b2b-website-design-company" element={<SalesforceConsulting />} />
    <Route path="/startup-web-design-agency" element={<SalesforceConsulting />} />
    <Route path="/best-web-development-companies-in-the-world" element={<SalesforceConsulting />} />
    <Route path="/web-design-and-marketing-company" element={<SalesforceConsulting />} />
    <Route path="/back-end-development-services" element={<SalesforceConsulting />} />
    <Route path="/seo-web-agency" element={<SalesforceConsulting />} />
    <Route path="/best-software-development-company-websites" element={<SalesforceConsulting />} />
    <Route path="/drupal-web-development-agency" element={<SalesforceConsulting />} />
    <Route path="/magento-web-agency" element={<SalesforceConsulting />} />
    <Route path="/business-website-price" element={<SalesforceConsulting />} />
    <Route path="/best-app-for-web-development" element={<SalesforceConsulting />} />
    <Route path="/asp-net-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/best-website-design-and-development-company" element={<SalesforceConsulting />} />
    <Route path="/mobile-website-developers" element={<SalesforceConsulting />} />
    <Route path="/interactive-web-development" element={<SalesforceConsulting />} />
    <Route path="/web-application-development-solutions" element={<SalesforceConsulting />} />
    <Route path="/web-3.0-development-services" element={<SalesforceConsulting />} />
    <Route path="/it-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/web-development-marketing" element={<SalesforceConsulting />} />
    <Route path="/reactjs-web-development-company" element={<SalesforceConsulting />} />
    <Route path="/top-web-design-companies-near-me" element={<SalesforceConsulting />} />

    <Route path="/digital-marketing" element={<SalesforceConsulting />} />
    <Route path="/ui-ux-design" element={<SalesforceConsulting />} />
    {/* SEO Services */}
    <Route path="/seo-audit-and-analysis" element={<SalesforceConsulting />} />
    <Route path="/on-page-seo-optimization" element={<SalesforceConsulting />} />
    <Route path="/technical-seo-services" element={<SalesforceConsulting />} />
    <Route path="/local-seo-services" element={<SalesforceConsulting />} />
    <Route path="/ecommerce-seo" element={<SalesforceConsulting />} />
    <Route path="/enterprise-seo-solutions" element={<SalesforceConsulting />} />
    <Route path="/seo-content-creation" element={<SalesforceConsulting />} />
    <Route path="/link-building-services" element={<SalesforceConsulting />} />
    <Route path="/seo-reporting-and-analytics" element={<SalesforceConsulting />} />
    <Route path="/seo-competitor-analysis" element={<SalesforceConsulting />} />
    <Route path="/seo-strategy-and-consulting" element={<SalesforceConsulting />} />
    <Route path="/seo-training-and-education" element={<SalesforceConsulting />} />
    <Route path="/seo-for-small-businesses" element={<SalesforceConsulting />} />
    <Route path="/seo-for-b2b-companies" element={<SalesforceConsulting />} />
    <Route path="/seo-for-saas-businesses" element={<SalesforceConsulting />} />
    <Route path="/seo-for-healthcare-providers" element={<SalesforceConsulting />} />
    <Route path="/seo-for-law-firms" element={<SalesforceConsulting />} />
    <Route path="/seo-for-real-estate-agencies" element={<SalesforceConsulting />} />
    <Route path="/seo-for-nonprofits" element={<SalesforceConsulting />} />
    <Route path="/seo-for-startups" element={<SalesforceConsulting />} />
    <Route path="/seo-for-manufacturers" element={<SalesforceConsulting />} />
    <Route path="/seo-for-restaurants" element={<SalesforceConsulting />} />
    <Route path="/seo-for-travel-and-hospitality" element={<SalesforceConsulting />} />
    <Route path="/seo-for-financial-services" element={<SalesforceConsulting />} />
    <Route path="/seo-for-automotive-industry" element={<SalesforceConsulting />} />
    <Route path="/seo-for-retail-and-ecommerce" element={<SalesforceConsulting />} />
    <Route path="/seo-for-b2c-brands" element={<SalesforceConsulting />} />
    <Route path="/voice-search-optimization" element={<SalesforceConsulting />} />
    <Route path="/video-seo" element={<SalesforceConsulting />} />
    <Route path="/image-seo" element={<SalesforceConsulting />} />
    <Route path="/mobile-seo" element={<SalesforceConsulting />} />
    <Route path="/international-seo" element={<SalesforceConsulting />} />
    <Route path="/seo-for-franchise-businesses" element={<SalesforceConsulting />} />
    <Route path="/seo-for-subscription-based-models" element={<SalesforceConsulting />} />
    <Route path="/seo-for-lead-generation" element={<SalesforceConsulting />} />
    <Route path="/seo-for-reputation-management" element={<SalesforceConsulting />} />
    <Route path="/seo-for-online-directories" element={<SalesforceConsulting />} />
    <Route path="/seo-for-blogs-and-publications" element={<SalesforceConsulting />} />
    <Route path="/seo-for-saas-product-pages" element={<SalesforceConsulting />} />
    <Route path="/seo-for-landing-pages" element={<SalesforceConsulting />} />
    <Route path="/seo-for-conversion-rate-optimization" element={<SalesforceConsulting />} />
    <Route path="/seo-for-user-experience" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-migrations" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-redesigns" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-audits" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-maintenance" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-hosting-and-infrastructure" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-security" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-speed-optimization" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-accessibility" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-internationalization" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-localization" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-personalization" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-scalability" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-reliability" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-extensibility" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-integration" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-adoption" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-training" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-support" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-consulting" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-implementation" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-managed-services" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-roadmap-and-strategy" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-optimization-and-tuning" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-data-migration-and-integration" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-security-and-compliance" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-customization-and-configuration" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-agile-transformation" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-devops-and-release-management" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-predictive-analytics-and-insights" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-intelligent-automation-and-workflows" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-conversational-ai-and-chatbots" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-omnichannel-engagement-and-experience" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-data-governance-and-stewardship" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-change-management-and-adoption" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-ecosystem-consulting-and-integration" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-managed-services-and-support" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-roadmap-and-strategic-planning" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-optimization-and-performance-tuning" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-data-migration-and-consolidation" element={<SalesforceConsulting />} />
    <Route path="/seo-for-website-security-and-compliance-consulting" element={<SalesforceConsulting />} />
    <Route path="/seo-for-ecommerce-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-b2b-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-saas-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-healthcare-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-law-firm-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-real-estate-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-nonprofit-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-startup-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-manufacturing-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-restaurant-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-travel-and-hospitality-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-financial-services-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-automotive-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-retail-and-ecommerce-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-b2c-brand-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-franchise-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-subscription-based-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-for-lead-generation-websites" element={<SalesforceConsulting />} />
    <Route path="/seo-in-tirupati" element={<SalesforceConsulting />} />
    <Route path="/web-development" element={<SalesforceConsulting />} />
    <Route path="/adwords-in-tirupati" element={<SalesforceConsulting />} />
  </Routes>
);

export default AppRoutesbackup;
